# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [ ]:
import numpy as np
arr = np.random.uniform(0, 20,28)
arr = arr.reshape((4,7))
minim = np.min(arr)
maxim = np.max(arr)
print(arr)
print("-----")
print(np.around((arr-minim)/(maxim-minim), decimals=1))


[[ 2.99410391 17.89058259  5.8989438   8.74223053  2.53181228  3.99127342
   8.29517958]
 [15.90338679  0.12147258  2.70941373  4.51503184 13.97009824 14.26185483
   9.04138124]
 [18.70899538  7.00953829 18.14348036 15.8880493  19.35784315 11.41635569
  16.36887214]
 [ 4.07479178  7.99034391 19.37902725  4.60203635 17.28145334 15.37263669
   6.1644845 ]]
-----
[[0.1 0.9 0.3 0.4 0.1 0.2 0.4]
 [0.8 0.  0.1 0.2 0.7 0.7 0.5]
 [1.  0.4 0.9 0.8 1.  0.6 0.8]
 [0.2 0.4 1.  0.2 0.9 0.8 0.3]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
import numpy as np
arr = np.random.randint(0, 10, 80)
arr = arr.reshape(8, 10)
k = 0
minim = 10000
for i in range(len(arr)):
  if sum(arr[i]) <minim:
    minim = sum(arr[i])
    k = i
print(arr)
print("----")
print(f'Индекс {k}\nСтрока {arr[i]}')

[[5 7 1 2 2 7 9 5 2 4]
 [8 0 0 7 3 9 9 8 7 4]
 [9 1 6 1 4 4 9 1 1 8]
 [8 6 0 7 3 0 0 1 4 8]
 [2 5 5 2 5 2 2 1 4 2]
 [7 3 5 1 3 9 2 5 1 7]
 [6 8 4 4 8 9 3 9 4 1]
 [1 4 6 1 9 1 4 9 3 1]]
----
Индекс 4
Строка [1 4 6 1 9 1 4 9 3 1]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [ ]:
import numpy as np
arr1 = np.array([int(i) for i in (input().split())]) 
arr2 = np.array([int(i) for i in (input().split())])
d = np.sqrt(np.sum(np.square(arr1-arr2)))
print(d)

0 0 0
1 1 1
1.7320508075688772


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [ ]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B= np.array([[3, -1], [2, 1]])
C=np.array([[7, 21], [11, 8], [8, 4]])
AX = np.dot(C*(-1), np.linalg.inv(B))
X = np.dot(np.linalg.inv(A), AX)
print(np.around(X, decimals = 2))

[[ 1.  0.]
 [-2.  1.]
 [ 3. -4.]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [2]:
import numpy as np
recipe = np.loadtxt('minutes_n_ingredients.csv', dtype = 'int32',delimiter=',', skiprows = 1)
print(recipe[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [3]:
print('Среднее значение ', np.mean(recipe[:,1:],0))
print('Максимальные значения ',np.max(recipe[:,1:],0))
print('Минимальные значения ',np.min(recipe[:,1:],0))
print('Медианы ',np.median(recipe[:,1:],0))

Среднее значение  [2.16010017e+04 9.05528000e+00]
Максимальные значения  [2147483647         39]
Минимальные значения  [0 1]
Медианы  [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [4]:
maxim = np.quantile(recipe[:,1], 0.75, axis = 0)
print(maxim)
print(recipe[recipe[:,1]<=maxim])

65.0
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [ 43407     35      7]
 [498432     65     15]
 [370915      5      4]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [9]:
a = np.count_nonzero(recipe[:,1] == 0)
recipe[recipe[:,1]==0] = 1
print( np.count_nonzero(recipe[:,1] == 0))

0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [11]:
a = np.unique(recipe[:,0])
print(len(a))

99522


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [19]:
a, num = np.unique(recipe[:,2], return_counts=True)
print(np.column_stack((a, num)))


[[    1   492]
 [    2   924]
 [    3  2884]
 [    4  5479]
 [    5  7874]
 [    6  9328]
 [    7 10579]
 [    8 10887]
 [    9 10542]
 [   10  9548]
 [   11  8262]
 [   12  6574]
 [   13  4985]
 [   14  3639]
 [   15  2583]
 [   16  1760]
 [   17  1237]
 [   18   787]
 [   19   566]
 [   20   376]
 [   21   214]
 [   22   161]
 [   23   105]
 [   24    68]
 [   25    50]
 [   26    28]
 [   27    16]
 [   28    16]
 [   29    12]
 [   30    12]
 [   31     3]
 [   32     1]
 [   33     2]
 [   34     1]
 [   35     3]
 [   37     1]
 [   39     1]]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [20]:
arr = recipe[recipe[:,2]<=5]
a = np.copy(arr)
print(a)
print('\n\n',recipe)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


 [[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993    140     14]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [26]:
a = recipe[:,2]/recipe[:,1]
print( max(a))

23.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [25]:
a = recipe[:,1].argsort()
b = recipe[a][-100:]
print(np.mean(b[:,2], axis = 0))

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [27]:
a = np.random.randint(recipe.shape[0], size = 10)
print(recipe[a])

[[ 25710     25     12]
 [326282     25      7]
 [469707     40      5]
 [477061     75     11]
 [315114     35     17]
 [189490   4330      2]
 [395174    120     14]
 [     1      1      1]
 [358436    120      8]
 [ 28624     15      4]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [30]:
a = np.mean(recipe[:,2], axis = 0)
print(recipe[recipe[:,2]<a])
print('----')
print((100*len(recipe[recipe[:,2]<a]))/len(recipe))

[[ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 ...
 [371794     35      8]
 [ 43407     35      7]
 [370915      5      4]]
----
58.989


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [31]:
a = np.append(recipe, np.zeros((recipe.shape[0],1), dtype = 'int32'), axis = 1)
a[np.logical_and(a[:,1]<=20,a[:,2]<=5)] = 1
a = a.copy()
print(a)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [     1      1      1      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [33]:
b = a[a[:,3] == 1]
print((100*len(b)/len(recipe)))

9.943


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [49]:
a1 = recipe[recipe[:,1]<10]
a2 = recipe[np.logical_and(recipe[:,1]>=10, recipe[:,1]<20)]
a3 = recipe[recipe[:,1]>=20]
maxim = min(len(a1), len(a2), len(a3))
b = np.array([[a1[:maxim-1],a2[:maxim-1],a3[:maxim-1]]])
print(b)

[[[[ 67660      5      6]
   [366174      7      9]
   [204134      5      3]
   ...
   [     1      1      1]
   [420725      5      3]
   [     1      1      1]]

  [[ 94746     10      6]
   [ 33941     18      9]
   [446597     15      5]
   ...
   [107094     10      4]
   [  9831     15      7]
   [335859     12     14]]

  [[127244     60     16]
   [ 23891     25      7]
   [157911     60     14]
   ...
   [ 92137     80      9]
   [168901     25      7]
   [392339     35     13]]]]
